version: "3.9"

services:
  backend:
    build: .
    container_name: mern_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/mern_db?authSource=admin
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mern_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
